"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import {ShieldCheck,Plus,RefreshCw,ArrowLeft,ArrowUpRight,Copy,Wallet as WalletIcon} from "lucide-react";
import * as api from "@/lib/sponsorproof";
import type {Campaign,Commitment,Summary,Wallet} from "@/lib/sponsorproof";
const when=(n:number)=>n?new Date(n*1000).toLocaleString():"Not opened";
const label=(v:string)=>v.replaceAll("_"," ").toLowerCase();
const pendingKey="sponsorproof.pending:"+api.ADDRESS;

export default function SponsorProofApp(){
 const[rows,setRows]=useState<Summary[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Campaign|null>(null);
 const[wallet,setWallet]=useState<Wallet|null>(null),[balance,setBalance]=useState("0"),[draft,setDraft]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const[message,setMessage]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState(""),[lastHash,setLastHash]=useState(""),[clock,setClock]=useState(()=>Date.now()/1000);
 const[statement,setStatement]=useState(""),[split,setSplit]=useState(""),[copied,setCopied]=useState("");
 const gate=useRef(false),revision=useRef(0),activeId=useRef("");
 const refresh=useCallback(async(page=offset,id=activeId.current)=>{const version=++revision.current;setLoading(true);setError("");try{const result=await api.list(page);const wanted=id||result.items[0]?.id;const detail=wanted?await api.campaign(wanted):null;const money=wallet?await api.credit(wallet.address):"0";if(version!==revision.current)return;setRows(result.items);setTotal(Number(result.total));setOffset(page);setSelected(detail);activeId.current=detail?.id||"";setBalance(money);}catch(e){if(version===revision.current)setError(api.errorText(e));}finally{if(version===revision.current)setLoading(false);}},[offset,wallet]);
 useEffect(()=>{void refresh(0);return()=>{revision.current++;};},[wallet]);
 useEffect(()=>{const tick=setInterval(()=>setClock(Date.now()/1000),1000);return()=>clearInterval(tick);},[]);
 useEffect(()=>{const saved=sessionStorage.getItem(pendingKey);if(saved&&/^0x[0-9a-f]{64}$/i.test(saved)){setPending(saved);setLastHash(saved);setMessage("An earlier transaction needs a receipt check before another action.");}},[]);
 useEffect(()=>{if(!wallet)return;const invalidate=()=>{setWallet(null);setMessage("Wallet or network changed. Reconnect to sign further actions.");};wallet.provider.on?.("accountsChanged",invalidate);wallet.provider.on?.("chainChanged",invalidate);return()=>{wallet.provider.removeListener?.("accountsChanged",invalidate);wallet.provider.removeListener?.("chainChanged",invalidate);};},[wallet]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:"inspect_sponsorship_agreement",title:"Inspect agreement",description:"Read an on-chain agreement and show it in SponsorProof. Does not sign or submit transactions.",inputSchema:{type:"object",properties:{id:{type:"string",pattern:"^sp-[1-9][0-9]*$"}},required:["id"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:unknown){const v=input as {id?:unknown};if(!v||Object.keys(v).length!==1||typeof v.id!=="string"||!/^sp-[1-9][0-9]*$/.test(v.id))throw new Error("Expected a valid agreement id.");const c=await api.campaign(v.id);revision.current++;setSelected(c);activeId.current=c.id;setDraft(false);setLoading(false);return{id:c.id,status:c.status,organizer_allocation:c.organizer_allocation,sponsor_allocation:c.sponsor_allocation,held_atto:c.held_atto};}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Proposed browser API is optional. */}return()=>lifecycle.abort();},[]);
 async function checkReceipt(hash:string){const result=await api.receipt(hash);sessionStorage.removeItem(pendingKey);setPending("");if(result==="rejected"){setError("The finalized transaction was rejected. No successful state change is claimed. Inspect its receipt for details.");setMessage("");return false;}setMessage("Transaction finalized successfully on StudioNet.");await refresh();return true;}
 async function transact(method:string,args:unknown[],value=0n){if(gate.current||pending)return false;if(!wallet){setError("Connect your wallet first.");return false;}gate.current=true;setBusy(true);setError("");setMessage("Confirm the action in your wallet.");try{const hash=await api.submit(wallet,method,args,value);setPending(hash);setLastHash(hash);sessionStorage.setItem(pendingKey,hash);setMessage("Submitted. Waiting for validator agreement and finalization…");return await checkReceipt(hash);}catch(e){setError(api.errorText(e));return false;}finally{gate.current=false;setBusy(false);}}
 async function copy(text:string,key:string){try{await navigator.clipboard.writeText(text);setCopied(key);}catch{setError("Select and copy the displayed challenge manually; clipboard access is unavailable.");}}
 const c=selected,party=!!c&&!!wallet&&(api.same(wallet.address,c.sponsor)||api.same(wallet.address,c.organizer)),organizer=!!c&&api.same(wallet?.address,c.organizer),sponsor=!!c&&api.same(wallet?.address,c.sponsor),disabled=busy||!!pending||!wallet;
 const act=(method:string,args:unknown[]=c?[c.id]:[],value=0n)=>void transact(method,args,value);
 const latest=c?.history.at(-1),original=c?.history[0];
 return <main className="workspace"><header><a className="brand" href="/"><ShieldCheck size={28}/>SponsorProof<span>SP / 01</span></a><div className="actions"><span className="network">StudioNet · simulated GEN</span><Button variant="outline" disabled={busy} onClick={async()=>{setError("");try{setWallet(await api.connect());}catch(e){setError(api.errorText(e));}}}><WalletIcon size={16}/>{wallet?api.short(wallet.address):"Connect wallet"}</Button></div></header>
 <section className="mast"><div><p className="eyebrow">SPONSORSHIP OPERATIONS</p><h1>Promises, with proof.</h1><p>Agreed commitments. Frozen evidence. Transparent allocations.</p></div><div className="actions"><Button variant="outline" disabled={busy||loading} onClick={()=>void refresh()} aria-label="Refresh agreements"><RefreshCw size={17}/></Button><Button onClick={()=>setDraft(!draft)}><Plus size={17}/>New agreement</Button></div></section>
 {message&&<div className="notice" role="status">{message} {pending&&<Button variant="outline" disabled={busy} onClick={async()=>{if(gate.current)return;gate.current=true;setBusy(true);setError("");try{await checkReceipt(pending);}catch(e){setError(api.errorText(e));}finally{gate.current=false;setBusy(false);}}}>Check receipt</Button>}</div>}
 {error&&<div className="notice error" role="alert">{error}</div>}{lastHash&&<p className="muted">Latest transaction: <a href={`https://explorer-studio.genlayer.com/transactions/${lastHash}`} target="_blank" rel="noreferrer">{api.short(lastHash)} ↗</a></p>}
 {wallet&&<div className="credit-bar"><span>Available to claim <strong>{api.gen(balance)} simulated GEN</strong></span><Button size="sm" variant="outline" disabled={disabled||balance==="0"} onClick={()=>act("claim",[])}>Claim credit</Button></div>}
 <div className="workgrid"><section className="ledger"><div className="section-title"><h2>{draft?"New agreement":c?c.title:"Agreements"}</h2><span>{loading?"Reading StudioNet…":`${total} agreement${total===1?"":"s"}`}</span></div>
 {draft?<AgreementForm disabled={disabled} onCancel={()=>setDraft(false)} onSubmit={async args=>{if(await transact("propose",args)){setDraft(false);const all=await api.list(0),page=Math.floor(Math.max(0,Number(all.total)-1)/20)*20,newest=await api.list(page);await refresh(page,newest.items.at(-1)?.id);}}}/>:
 !c?<div className="empty"><ShieldCheck size={38}/><h3>{loading?"Reading the agreement register…":"Every payment starts with an agreement."}</h3><p>Lock 1–4 public web commitments and their payment weights. Both parties approve the terms before funding.</p><Button variant="outline" onClick={()=>setDraft(true)}>Draft an agreement <ArrowUpRight size={16}/></Button></div>:<>
 <nav className="agreement-nav" aria-label="Choose agreement">{rows.map(row=><Button key={row.id} variant={row.id===c.id?"secondary":"ghost"} size="sm" onClick={()=>{setDraft(false);setStatement("");setSplit("");void refresh(offset,row.id);}}>{row.id} · {row.title.slice(0,27)}</Button>)}{offset>0&&<Button variant="ghost" onClick={()=>void refresh(Math.max(0,offset-20),"")}>Previous</Button>}{offset+20<total&&<Button variant="ghost" onClick={()=>void refresh(offset+20,"")}>Next</Button>}</nav>
 <div className="agreement-body"><div className="actions"><span className={`badge ${c.status.toLowerCase()}`}>{label(c.status)}</span><span className="muted">{c.id} · Budget {api.gen(c.budget_atto)} simulated GEN</span></div>
 <div className="parties"><div><span>Sponsor</span><code>{c.sponsor}</code></div><div><span>Organizer</span><code>{c.organizer}</code></div></div>
 <div className="deadlines"><span>Evidence closes <strong>{when(c.deadline)}</strong></span><span>Review closes <strong>{when(c.review_deadline)}</strong></span><span>Unresolved timeout <strong>{when(c.hard_deadline)}</strong></span></div>
 <details><summary>Agreed settlement and evidence rules</summary><p>Fulfilled pays 100% of a commitment’s allocation; partial pays 50%; not fulfilled refunds it. Inconclusive allocations are held for a mutual split, then refunded to the sponsor at the agreed seven-day timeout. This is not a finding of non-delivery. Only text at the agreed URLs is assessed. Captures prove a point-in-time publication, not continuous placement or audience reach.</p><p>Each source needs its wallet-bound challenge. Captures cannot be replaced. Both parties may submit one argument in the shared appeal round; no new pages are introduced after the deadline.</p><p className="muted">Terms digest <code>{c.terms_digest}</code></p></details>
 <div className="actions stage-actions">
 {c.status==="PROPOSED"&&organizer&&<Button disabled={disabled||clock>=c.deadline} onClick={()=>act("accept",[c.id,c.terms_digest])}>Accept locked terms</Button>}
 {c.status==="ACCEPTED"&&sponsor&&<Button disabled={disabled||clock>=c.deadline} onClick={()=>act("fund",[c.id],BigInt(c.budget_atto))}>Fund exact {api.gen(c.budget_atto)} GEN</Button>}
 {["PROPOSED","ACCEPTED"].includes(c.status)&&party&&<Button disabled={disabled} variant="outline" onClick={()=>act("cancel_unfunded")}>Cancel unfunded agreement</Button>}
 {c.status==="ACTIVE"&&party&&!c.seals.some(x=>api.same(x,wallet?.address))&&Object.keys(c.evidence).length===c.commitments.length&&<Button disabled={disabled} variant="outline" onClick={()=>act("seal_evidence")}>Seal evidence for early review</Button>}
 {c.status==="ACTIVE"&&(clock>=c.deadline||c.seals.length===2)&&<Button disabled={disabled||clock+c.review_seconds>=c.hard_deadline} onClick={()=>act("evaluate")}>Evaluate delivery</Button>}
 {c.status==="APPEAL_OPEN"&&clock>=c.review_deadline&&clock<c.hard_deadline&&<Button disabled={disabled} onClick={()=>act("resolve_appeal")}>Resolve shared appeal</Button>}
 {["REVIEW","RESOLVED"].includes(c.status)&&clock>=c.review_deadline&&<Button disabled={disabled} onClick={()=>act("settle")}>Settle conclusive allocations</Button>}
 {c.funded&&!["SETTLED","TIMEOUT_REFUND"].includes(c.status)&&clock>=c.hard_deadline&&<Button disabled={disabled} variant="outline" onClick={()=>act("expire")}>Apply agreed timeout</Button>}
 </div>{!wallet&&<p className="muted">Viewing is wallet-free. Connect to sign actions permitted by the agreement.</p>}
 <div className="allocation"><div><span>Organizer allocation</span><strong>{api.gen(c.organizer_allocation)}<small>simulated GEN</small></strong></div><div><span>Sponsor refund</span><strong>{api.gen(c.sponsor_allocation)}<small>simulated GEN</small></strong></div><div><span>{c.allocated?"Still held":"Escrow funded"}</span><strong>{api.gen(c.allocated?c.held_atto:c.funded?c.budget_atto:"0")}<small>simulated GEN</small></strong></div></div>
 <h3>Locked commitments</h3>{c.commitments.map((row,i)=>{const evidence=c.evidence[row.id],decision=latest?.decision.commitments.find(x=>x.id===row.id),before=original?.decision.commitments.find(x=>x.id===row.id);const challenge=["SPONSORPROOF-V1","studionet",api.ADDRESS.toLowerCase(),c.id,row.id,c.organizer.toLowerCase(),c.terms_digest].join("|");return <article className="commitment" key={row.id}><div className="commitment-heading"><div><span className="eyebrow">{String(i+1).padStart(2,"0")} / {row.weight}% OF BUDGET</span><h3>{row.title}</h3></div>{decision&&<span className={`badge ${decision.outcome.toLowerCase()}`}>{label(decision.outcome)}</span>}</div><p>{row.requirement}</p><a className="source-link" href={row.url} target="_blank" rel="noreferrer">Agreed source <ArrowUpRight size={15}/><span>{row.url}</span></a>
 {!evidence&&<details open={organizer&&c.status==="ACTIVE"}><summary>Publication challenge</summary><p>Add this exact line to the agreed page before capturing. It binds the publication to this organizer, agreement and commitment.</p><code className="block-code">{challenge}</code><Button variant="outline" size="sm" onClick={()=>void copy(challenge,row.id)}><Copy size={15}/>{copied===row.id?"Copied":"Copy challenge"}</Button></details>}
 {!evidence&&organizer&&c.status==="ACTIVE"&&<Button disabled={disabled||clock>=c.deadline||c.seals.length>0} onClick={()=>act("capture",[c.id,row.id])}>Capture agreed page</Button>}
 {evidence&&<details><summary>Inspect frozen evidence · {when(evidence.captured_at)}</summary><p className="muted">SHA-256 <code>{evidence.sha256}</code></p><pre className="evidence-text">{evidence.text.split("\n").map((line,j)=>`${j+1}  ${line}`).join("\n")}</pre></details>}
 {decision&&<div className="decision"><p>{decision.reason}</p>{decision.refs.map(ref=><blockquote key={ref.line}><span>Source line {ref.line}</span>{ref.excerpt}</blockquote>)}{latest?.phase==="appeal"&&before&&<details><summary>Original decision: {label(before.outcome)}</summary><p>{before.reason}</p>{before.refs.map(ref=><blockquote key={ref.line}>Line {ref.line}: {ref.excerpt}</blockquote>)}</details>}</div>}</article>;})}
 {party&&["REVIEW","APPEAL_OPEN"].includes(c.status)&&clock<c.review_deadline&&!Object.keys(c.appeals).some(x=>api.same(x,wallet?.address))&&<form className="action-form" onSubmit={e=>{e.preventDefault();act("appeal",[c.id,statement]);}}><h3>Request reconsideration</h3><p>One statement per party. Both arguments are considered after the shared window closes. Cite the existing evidence; new pages cannot be added.</p><label>Your argument<textarea value={statement} onChange={e=>setStatement(e.target.value)} minLength={25} maxLength={1200} required/></label><Button disabled={disabled}>Submit appeal argument</Button></form>}
 {Object.keys(c.appeals).length>0&&<details><summary>Both parties’ appeal arguments</summary>{Object.entries(c.appeals).map(([address,text])=><div key={address}><strong>{api.same(address,c.sponsor)?"Sponsor":"Organizer"}</strong><p>{text}</p></div>)}</details>}
 {c.status==="HELD"&&party&&clock<c.hard_deadline&&<form className="action-form" onSubmit={e=>{e.preventDefault();try{const n=api.atto(split);if(n>BigInt(c.held_atto))throw new Error("Split exceeds held funds.");act("propose_split",[c.id,n]);}catch(err){setError(api.errorText(err));}}}><h3>Resolve held funds together</h3><p>The counterparty must accept the exact split. Conclusive allocations cannot be changed.</p><label>Organizer share of held funds (GEN)<input inputMode="decimal" value={split} onChange={e=>setSplit(e.target.value)} required/></label><Button disabled={disabled} variant="outline">Propose held-funds split</Button>{c.split_proposal&&<div className="notice"><p>Proposed organizer share: {api.gen(c.split_proposal.organizer_atto)} GEN. The rest refunds the sponsor.</p><code>{c.split_proposal.digest}</code>{!api.same(c.split_proposal.proposer,wallet?.address)&&<Button disabled={disabled} onClick={()=>act("accept_split",[c.id,c.split_proposal!.digest])} type="button">Accept this exact split</Button>}</div>}</form>}
 {c.history.length>0&&<details><summary>Immutable decision records and digests</summary><pre>{JSON.stringify(c.history,null,2)}</pre></details>}{c.resolution&&<p className="muted">Resolution: {label(c.resolution)}</p>}
 </div></>}
 </section><aside className="policy"><p className="eyebrow">THE SETTLEMENT RULE</p><h2>Judgment on-chain.<br/>Arithmetic in code.</h2><dl><div><dt>Fulfilled</dt><dd>100% of allocation</dd></div><div><dt>Partial</dt><dd>50% of allocation</dd></div><div><dt>Not fulfilled</dt><dd>Refund allocation</dd></div><div><dt>Inconclusive</dt><dd>Hold for resolution</dd></div></dl><p>Validators independently agree on each outcome. Explanations may differ. Evidence comes from the URL both parties accepted.</p><p>StudioNet uses simulated GEN. This is not production money custody or a guarantee that source claims are true.</p><a href={api.EXPLORER} target="_blank" rel="noreferrer">Inspect intelligent contract ↗</a><code className="contract-address">{api.ADDRESS}</code><a href={`${api.REPO}/blob/main/docs/SPONSORPROOF_REVIEW.md`} target="_blank" rel="noreferrer">Reviewer guide ↗</a></aside></div>
 <footer><a href={api.EXPLORER} target="_blank" rel="noreferrer">StudioNet contract</a> · <a href={`${api.REPO}/blob/main/contracts/sponsorproof.py`} target="_blank" rel="noreferrer">Source code</a> · Public agreement records; do not submit private information.</footer></main>;
}

function AgreementForm({disabled,onCancel,onSubmit}:{disabled:boolean;onCancel:()=>void;onSubmit:(args:unknown[])=>Promise<void>}){
 const[title,setTitle]=useState(""),[organizer,setOrganizer]=useState(""),[budget,setBudget]=useState("0.001"),[deadline,setDeadline]=useState(""),[review,setReview]=useState("60"),[error,setError]=useState("");
 const[rows,setRows]=useState<Omit<Commitment,"id">[]>([{title:"",requirement:"",url:"",weight:100}]);
 const weight=rows.reduce((sum,r)=>sum+(Number.isFinite(r.weight)?r.weight:0),0);
 function update(index:number,field:string,value:string|number){setRows(rows.map((r,i)=>i===index?{...r,[field]:value}:r));}
 return <form className="form-slice" onSubmit={async e=>{e.preventDefault();setError("");try{if(!api.validAddress(organizer))throw new Error("Enter the organizer’s wallet address.");if(weight!==100||rows.some(r=>!Number.isInteger(r.weight)||r.weight<1))throw new Error("Integer weights must total 100%.");const amount=api.atto(budget);if(amount<10n**15n||amount>1000n*10n**18n)throw new Error("Budget must be 0.001–1000 GEN.");const end=Math.floor(new Date(deadline).getTime()/1000),seconds=Number(review)*60;if(!Number.isFinite(end)||end<Date.now()/1000+60)throw new Error("Choose a deadline at least one minute ahead.");if(!Number.isInteger(seconds)||seconds<60||seconds>86400)throw new Error("Review window must be 1–1440 minutes.");await onSubmit([title.trim(),organizer,JSON.stringify(rows),amount,end,seconds]);}catch(err){setError(api.errorText(err));}}}>
 <Button type="button" variant="ghost" onClick={onCancel}><ArrowLeft size={16}/>Back</Button><p>No funds move when proposing. The organizer accepts the locked terms before the sponsor funds the exact budget.</p>
 <label>Campaign name<input value={title} onChange={e=>setTitle(e.target.value)} minLength={3} maxLength={100} required placeholder="September developer workshop"/></label><label>Organizer wallet<input value={organizer} onChange={e=>setOrganizer(e.target.value)} required placeholder="0x…"/></label>
 <div className="form-grid"><label>Budget (simulated GEN)<input inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)} required/></label><label>Delivery deadline (your local time)<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} required/></label><label>Shared review window (minutes)<input type="number" min={1} max={1440} step={1} value={review} onChange={e=>setReview(e.target.value)} required/></label></div>
 <h3>Public web commitments <span className={weight!==100?"weight-error":""}>{weight}/100%</span></h3>
 {rows.map((row,i)=><fieldset key={i}><legend>Commitment {i+1}</legend><div className="form-grid"><label>Title<input value={row.title} onChange={e=>update(i,"title",e.target.value)} minLength={3} maxLength={80} required/></label><label>Weight (%)<input type="number" min={1} max={100} step={1} value={Number.isNaN(row.weight)?"":row.weight} onChange={e=>update(i,"weight",Number(e.target.value))} required/></label></div><label>Delivery requirement<textarea value={row.requirement} onChange={e=>update(i,"requirement",e.target.value)} minLength={25} maxLength={1600} placeholder="Describe full and partial delivery and what this page must show." required/></label><label>Exact public evidence URL<input type="url" value={row.url} onChange={e=>update(i,"url",e.target.value)} placeholder="https://your-publication.com/sponsors" required maxLength={400}/></label>{rows.length>1&&<Button type="button" variant="ghost" onClick={()=>setRows(rows.filter((_,j)=>j!==i))}>Remove commitment</Button>}</fieldset>)}
 {rows.length<4&&<Button type="button" variant="outline" onClick={()=>setRows([...rows,{title:"",requirement:"",url:"",weight:0}])}><Plus size={16}/>Add commitment</Button>}
 <p className="terms-notice">By proposing, you agree to 100% / 50% / 0% allocation rules, a shared appeal round, and refund of unresolved funds to the sponsor seven days after the delivery deadline. The organizer must explicitly accept the same terms. Only text evidence is supported; private analytics and continuous placement are not verified.</p>
 {error&&<p className="notice error" role="alert">{error}</p>}<Button disabled={disabled||weight!==100}>Propose locked agreement</Button>{disabled&&<p className="muted">Connect your wallet and finish any pending transaction to propose.</p>}</form>;
}
